#!/usr/bin/env python3
"""Fixtures used by the integration tests for the github org client."""
TEST_PAYLOAD = [
  (
    {
      "repos_url": "https://api.github.com/orgs/google/repos",
    },
    [
      {
        "id": 7697149,
        "name": "episodes.dart",
        "private": False,
        "owner": {
          "login": "google",
          "id": 1342004,
        },
        "fork": False,
        "url": "https://api.github.com/repos/google/episodes.dart",
        "created_at": "2013-01-19T00:31:37Z",
        "updated_at": "2019-09-23T11:53:58Z",
        "has_issues": True,
        "forks": 22,
        "default_branch": "master",
        "license": {
          "key": "bsd-3-clause",
          "name": "BSD 3-Clause \"New\" or \"Revised\" License",
          "spdx_id": "BSD-3-Clause",
          "url": "https://api.github.com/licenses/bsd-3-clause",
          "node_id": "MDc6TGljZW5zZTU=",
        },
      },
      {
        "id": 7776515,
        "name": "cpp-netlib",
        "private": False,
        "owner": {
          "login": "google",
          "id": 1342004,
        },
        "fork": False,
        "url": "https://api.github.com/repos/google/cpp-netlib",
        "created_at": "2013-01-23T14:45:32Z",
        "updated_at": "2019-11-15T02:26:32Z",
        "has_issues": True,
        "forks": 59,
        "default_branch": "master",
        "license": {
          "key": "bsl-1.0",
          "name": "Boost Software License 1.0",
          "spdx_id": "BSL-1.0",
          "url": "https://api.github.com/licenses/bsl-1.0",
          "node_id": "MDc6TGljZW5zZTI4",
        },
      },
      {
        "id": 7968417,
        "name": "dagger",
        "private": False,
        "owner": {
          "login": "google",
          "id": 1342004,
        },
        "fork": False,
        "url": "https://api.github.com/repos/google/dagger",
        "created_at": "2013-02-01T15:31:36Z",
        "updated_at": "2019-11-15T20:22:11Z",
        "has_issues": True,
        "forks": 2380,
        "default_branch": "master",
        "license": {
          "key": "apache-2.0",
          "name": "Apache License 2.0",
          "spdx_id": "Apache-2.0",
          "url": "https://api.github.com/licenses/apache-2.0",
          "node_id": "MDc6TGljZW5zZTI=",
        },
      },
      {
        "id": 8165161,
        "name": "ios-webkit-debug-proxy",
        "private": False,
        "owner": {
          "login": "google",
          "id": 1342004,
        },
        "fork": False,
        "url": "https://api.github.com/repos/google/ios-webkit-debug-proxy",
        "created_at": "2013-02-13T00:43:40Z",
        "updated_at": "2019-11-15T22:40:50Z",
        "has_issues": True,
        "forks": 552,
        "default_branch": "master",
        "license": {
          "key": "other",
          "name": "Other",
          "spdx_id": "NOASSERTION",
          "url": None,
          "node_id": "MDc6TGljZW5zZTA=",
        },
      },
      {
        "id": 8459994,
        "name": "google.github.io",
        "private": False,
        "owner": {
          "login": "google",
          "id": 1342004,
        },
        "fork": False,
        "url": "https://api.github.com/repos/google/google.github.io",
        "created_at": "2013-02-28T21:33:34Z",
        "updated_at": "2019-11-15T09:07:39Z",
        "has_issues": True,
        "forks": 651,
        "default_branch": "master",
        "license": None,
      },
      {
        "id": 8566972,
        "name": "kratu",
        "private": False,
        "owner": {
          "login": "google",
          "id": 1342004,
        },
        "fork": False,
        "url": "https://api.github.com/repos/google/kratu",
        "created_at": "2013-03-04T22:52:33Z",
        "updated_at": "2019-11-15T22:22:16Z",
        "has_issues": True,
        "forks": 45,
        "default_branch": "master",
        "license": {
          "key": "apache-2.0",
          "name": "Apache License 2.0",
          "spdx_id": "Apache-2.0",
          "url": "https://api.github.com/licenses/apache-2.0",
          "node_id": "MDc6TGljZW5zZTI=",
        },
      },
      {
        "id": 8858648,
        "name": "build-debian-cloud",
        "private": False,
        "owner": {
          "login": "google",
          "id": 1342004,
        },
        "fork": True,
        "url": "https://api.github.com/repos/google/build-debian-cloud",
        "created_at": "2013-03-19T19:29:53Z",
        "updated_at": "2019-11-15T22:04:38Z",
        "has_issues": False,
        "forks": 63,
        "default_branch": "master",
        "license": {
          "key": "other",
          "name": "Other",
          "spdx_id": "NOASSERTION",
          "url": None,
          "node_id": "MDc6TGljZW5zZTA=",
        },
      },
      {
        "id": 9060347,
        "name": "traceur-compiler",
        "private": False,
        "owner": {
          "login": "google",
          "id": 1342004,
        },
        "fork": False,
        "url": "https://api.github.com/repos/google/traceur-compiler",
        "created_at": "2013-03-29T22:52:29Z",
        "updated_at": "2019-11-15T21:20:11Z",
        "has_issues": True,
        "forks": 774,
        "default_branch": "master",
        "license": {
          "key": "apache-2.0",
          "name": "Apache License 2.0",
          "spdx_id": "Apache-2.0",
          "url": "https://api.github.com/licenses/apache-2.0",
          "node_id": "MDc6TGljZW5zZTI=",
        },
      },
      {
        "id": 9065917,
        "name": "firmata.py",
        "private": False,
        "owner": {
          "login": "google",
          "id": 1342004,
        },
        "fork": False,
        "url": "https://api.github.com/repos/google/firmata.py",
        "created_at": "2013-03-30T11:46:52Z",
        "updated_at": "2019-04-08T18:31:52Z",
        "has_issues": True,
        "forks": 12,
        "default_branch": "master",
        "license": {
          "key": "apache-2.0",
          "name": "Apache License 2.0",
          "spdx_id": "Apache-2.0",
          "url": "https://api.github.com/licenses/apache-2.0",
          "node_id": "MDc6TGljZW5zZTI=",
        },
      },
    ],
    [
      "episodes.dart",
      "cpp-netlib",
      "dagger",
      "ios-webkit-debug-proxy",
      "google.github.io",
      "kratu",
      "build-debian-cloud",
      "traceur-compiler",
      "firmata.py",
    ],
    [
      "dagger",
      "kratu",
      "traceur-compiler",
      "firmata.py",
    ],
  ),
]
